### ISSUE TITLE
Adapt Idepix OLCI to updated OLCI O2A Harmonisation

### ISSUE THREAD

**Issue by dolaf** [bcdev/snap-idepix#13]
Once update of OLCI O2A Harmonisation is available (see [https://senbox.atlassian.net/browse/SIIITBX-339]), adapt Idepix OLCI. I.e., module version of O2A Harmonisation needs to be updated. Further cross-check outputs of updated O2A Harmonisation and see if more adaptations are needed.

**Comment by marpet** [comment]
this is closed already
