### ISSUE TITLE
Update Tensorflow library to version 1.15

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#14]
Currently we still use verrsion Version 1.9.0-rc1 (June 2018) of Tensorflow.
Meanwhile version 1.15.0 is available as Java library. We should update it. 
This might improve performance and might solve problems with loading dependencies.
After switching to the new version we need to compare the processing results with the old library version.

**Comment by marpet** [comment]
Meanwhile, we could use even later versions:
https://github.com/tensorflow/java/#tensorflow-version-support
But this might introduces compatibility issues. Needs to be tested. One step after the other.

**Comment by marpet** [comment]
Update to later version can be done when needed-

**Comment by marpet** [comment]
Reverted the update to the new version. It seems to be slower.
Needs more careful investigation, also by scientists.

**Comment by octoflarbc** [comment]
We use TF 2.x in Python. Having a Java version which is compatible to TF 2.x would be great.

**Comment by marpet** [comment]
Why is it necessary for you to use the same version?

**Comment by octoflarbc** [comment]
I did not say the same version but version compatible with TF 2.x. There are significant improvements between TF versions 1.x and 2.x. And TF 2.0 is released since almost two years now.
