### ISSUE TITLE
Duplicated cloud shadow near scene edge in OLCI data

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#26]
In some cases, the cloud shadow algorithm creates duplicated shadows but in the opposite direction.

![duplicated-shadows](https://user-images.githubusercontent.com/204590/100319083-61bd7f80-2fbf-11eb-9432-27229baccd59.png)

**Comment by dagmarM** [comment]
There is a fix to handle pixels close to the scene rim correctly. 
The example shows the new cloud shadow mask (magenta, top) and another example, in which the rim has not been processed (bottom). This has been the area, where the strange duplication has taken place in the beginning. 
![grafik](https://user-images.githubusercontent.com/26061443/112472000-e0a7a680-8d6c-11eb-91fa-12f08f5222d6.png)
