### ISSUE TITLE
S2 Idepix IDEPIX_CLEAR_WATER flags mountains as water

### ISSUE THREAD

**Issue by JanWev** [bcdev/snap-idepix#30]
@marpet and @dolaf 
I have just today discovered that the CLEAR_WATER flag, does not make sense in mountainous areas, as mountains are flagged as clear water. I will look into solving this methodologically but will then need someone for implementation. We should then release this with the update of the mountain shadow "fix", where we reduce to the hillshade algo.

**Comment by JanWev** [comment]
We need to investigate this in conjunction with #22 . As the wrong water delivers the best mountain shadow compared to the other two.

**Comment by jorritscholze** [comment]
The flags SNOW, BRIGHT_WHITE and MOUNTAIN_SHADOW were added to CLEAR_WATER expression.

The new nbw shows a CLEAR_WATER_MASK. Although the coutermask CLEAR_LAND works fine and does not flag water areas.
