### ISSUE TITLE
Update jblas library to 1.2.5

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#37]
Jblas version is currently 1.2.3, but already 1.2.5 is available. This is also 
the version used in SNAP.
jblas has issues with dependencies to native libraries. See:
https://senbox.atlassian.net/browse/SITBX-769

https://github.com/jblas-project/jblas/issues/87
https://github.com/jblas-project/jblas/issues/98

When working on S2 anyway, the please test if the library can be updated easily. Then we have at least the same version in idepix and snap and the same problems, not otherones.

**Comment by TonioF** [comment]
jblas 1.2.5 been tested to work on calvalus, is updated now.
