### ISSUE TITLE
S2 Idepix creates very large log

### ISSUE THREAD

**Issue by TonioF** [bcdev/snap-idepix#43]
When running the S2 Idepix with cloudComputation, some lines (
WARNING: org.esa.snap.idepix.s2msi.operators.cloudshadow.S2IdepixCloudShadowOp: indecesRelativMaxInArray x.length=1
WARNING: org.esa.snap.idepix.s2msi.operators.cloudshadow.PotentialCloudShadowAreaIdentifier: identifyPotentialCloudShadowPLUS: cloudPath.length=1
) were output very often, obscuring any other lines and even stacktraces. These logs either need to go or set to a lower log resolution.

**Comment by marpet** [comment]
I would vote to remove them.
If they are logged often it takes also some share of the processing time, even if they are not printed to the console.

**Comment by TonioF** [comment]
Closed by #45 .
