### ISSUE TITLE
Improve performance of OLCI IdePix

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#74]
The performance shall be improved

**Comment by martin-boettcher** [comment]
Idepix.Olci mainly suffered from slow CTP computation for cloud shadow. CTP was computed using tensorflow. The modification of tensorflow calls from call per pixel to one call per tile pushed down CTP from more than 70% to 6% of computing time share.

**Comment by martin-boettcher** [comment]
resolved in 9.0.6
