### ISSUE TITLE
Improve performance of S2 MSI IdePix

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#75]
The performance of the S2 MSI IdePix shall be improved

**Comment by martin-boettcher** [comment]
Idepix MSI algorithm re-implemented as a single-pass loop over the pixels with a multi-line accumulator to avoid full-image intermediate results. Optimisation has pushed down S2CloudPostprocess from more than 70% to 15% of the processing time. Memory consumption is reduced.
Implemented in version 9.0.6 .
